------------------------------------------------------------------------------
---- Include changes related to other datatypes except spatial types here ----
------------------------------------------------------------------------------

-- complain if script is sourced in psql, rather than via ALTER EXTENSION
\echo Use "ALTER EXTENSION ""babelfishpg_common"" UPDATE TO '6.2.0'" to load this file. \quit

CREATE OR REPLACE FUNCTION sys.bit2datetime(IN num sys.BIT)
RETURNS sys.DATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00.0' AS sys.DATETIME) OPERATOR(sys.+) (CASE WHEN CAST(num AS INT) != 0 THEN 1 ELSE 0 END);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.numeric2datetime(IN num NUMERIC)
RETURNS sys.DATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00.0' AS sys.DATETIME) OPERATOR(sys.+) CAST(num AS FLOAT8);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.float8datetime(IN num FLOAT8)
RETURNS sys.DATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00.0' AS sys.DATETIME) OPERATOR(sys.+) num;
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.float4datetime(IN num FLOAT4)
RETURNS sys.DATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00.0' AS sys.DATETIME) OPERATOR(sys.+) CAST(num AS FLOAT8);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.int2datetime(IN num INT)
RETURNS sys.DATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00.0' AS sys.DATETIME) OPERATOR(sys.+) num;
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.bigint2datetime(IN num BIGINT)
RETURNS sys.DATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00.0' AS sys.DATETIME) OPERATOR(sys.+) CAST(num AS INT);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.smallint2datetime(IN num SMALLINT)
RETURNS sys.DATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00.0' AS sys.DATETIME) OPERATOR(sys.+) CAST(num AS INT);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.money2datetime(IN num FIXEDDECIMAL)
RETURNS sys.DATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00.0' AS sys.DATETIME) OPERATOR(sys.+) CAST(num AS FLOAT8);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.bit2smalldatetime(IN num sys.BIT)
RETURNS sys.SMALLDATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00' AS sys.SMALLDATETIME) OPERATOR(sys.+) (CASE WHEN CAST(num AS INT) != 0 THEN 1 ELSE 0 END);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.numeric2smalldatetime(IN num NUMERIC)
RETURNS sys.SMALLDATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00' AS sys.SMALLDATETIME) OPERATOR(sys.+) CAST(num AS FLOAT8);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.float8smalldatetime(IN num FLOAT8)
RETURNS sys.SMALLDATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00' AS sys.SMALLDATETIME) OPERATOR(sys.+) num;
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.float4smalldatetime(IN num FLOAT4)
RETURNS sys.SMALLDATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00' AS sys.SMALLDATETIME) OPERATOR(sys.+) CAST(num AS FLOAT8);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.int2smalldatetime(IN num INT)
RETURNS sys.SMALLDATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00' AS sys.SMALLDATETIME) OPERATOR(sys.+) num;
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.bigint2smalldatetime(IN num BIGINT)
RETURNS sys.SMALLDATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00' AS sys.SMALLDATETIME) OPERATOR(sys.+) CAST(num AS INT);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.smallint2smalldatetime(IN num SMALLINT)
RETURNS sys.SMALLDATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00' AS sys.SMALLDATETIME) OPERATOR(sys.+) CAST(num AS INT);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;

CREATE OR REPLACE FUNCTION sys.money2smalldatetime(IN num FIXEDDECIMAL)
RETURNS sys.SMALLDATETIME
AS $$
    SELECT CAST('1900-01-01 00:00:00' AS sys.SMALLDATETIME) OPERATOR(sys.+) CAST(num AS FLOAT8);
$$
LANGUAGE SQL IMMUTABLE STRICT PARALLEL SAFE;
